export const FETCH_ALL_TAGS = 'FETCH_ALL_TAGS';
export const FETCH_TAG_BY_ID = 'FETCH_TAG_BY_ID';
export const FETCH_ALL_CATEGORIES = 'FETCH_ALL_CATEGORIES';
export const FETCH_CATEGORY_BY_ID = 'FETCH_CATEGORY_BY_ID';
export const FETCH_ALL_PAGES = 'FETCH_ALL_PAGES';
export const FETCH_PAGE_BY_ID = 'FETCH_PAGE_BY_ID';
export const FETCH_ALL_POSTS = 'FETCH_ALL_POSTS';
export const FETCH_POST_BY_ID = 'FETCH_POST_BY_ID';
